### ISSUE TITLE
hosts would be remove when cluster update

### ISSUE THREAD

**Issue by kevin21th** [alipay/sofa-mosn#104]
when update cluster which type is Cluster_EDS,  the hosts would be remove.

function call clusterAdapter.ClusterAdap.TriggerClusterUpdate(cluster.Name, cluster.Hosts) in callback
cluster.Hosts have 0 element when cluster type is Cluster_EDS

**Comment by Lingtaonju** [comment]
fix:
when cluster type is xdsapi.Cluster_EDS, only added/update cluster but not hosts
