### ISSUE TITLE
HTTP1 client receive status 200 when upstream server is closed

### ISSUE THREAD

**Issue by nejisama** [alipay/sofa-mosn#106]
scene:
HTTP1 client -> mesh(HTTP1) -> mesh(HTTP1) ->  HTTP1 Server ( closed)

client receive status code 200

**Comment by nejisama** [comment]
HTTP2 - HTTP1 - HTTP1 - HTTP2 also get 200

**Comment by Lingtaonju** [comment]
Reason: 
lost response status between mosns make this bug happen.
