### ISSUE TITLE
Support cluster update&delete in ADS integration

### ISSUE THREAD

**Issue by ldxdl** [alipay/sofa-mosn#116]
In ADS dynamic config mode, cluster update&delete is required to perform on ADS config change

**Comment by Lingtaonju** [comment]
初步方案 

# 当前能力
1. 当前内部接口 `ClusterManager` 用于管理 `cluster`，其中，添加/更新、删除 cluster 的接口均已存在，基本上满足现状要求，但是：

2. 当前 cluster 的更新和创建使用的是一个函数，无论 相同 clustername 的 cluster 是否本身已经存在，均会根据配置创建一个新的cluster，并重新写内存, 这有个问题就是，在单独更新 cluster 的时候，会丢失 hosts

3. 需要修改的地方
   3.1.针对 2 中的问题，需要在单独更新 cluster 的时候，提供 hosts 的迁移能力
   3.2 调用 clustermanager 的 adapter 的设计需要统一

# 方案设计
1. 	针对 3.1，修改 `TriggerClusterAddedOrUpdate` ，在 cluster 已经存在的情况下，获取origin cluster 的 hosts，并保存到新创建的 cluster 中去，代码：

```go
// TriggerClusterAddedOrUpdate
// Added cluster when cluster doesn't exsit
// or Update Cluster when cluster already exsit, and hosts remain unchanged
func (ca *Adapter) TriggerClusterAddedOrUpdate(cluster v2.Cluster) error {
	var hosts []types.Host
	
	// if cluster already exist, then get store hosts
	if v := ca.clusterMng.GetCluster(cluster.Name); v != nil{
		pcc := v.(*primaryCluster).cluster
		if concretedCluster, ok := pcc.(*simpleInMemCluster); ok {
			hosts = concretedCluster.hosts
		}
	}
	
	// get or update cluster
	if !ca.clusterMng.AddOrUpdatePrimaryCluster(cluster) {
		return fmt.Errorf("TriggerClusterAdded: AddOrUpdatePrimaryCluster failure, cluster name = %s", cluster.Name)
	}
	
	// if cluster alreay exist
	if len(hosts) > 0 {
		v := ca.clusterMng.GetCluster(cluster.Name)
		pcc := v.(*primaryCluster).cluster
		if concretedCluster,ok :=pcc.(*simpleInMemCluster);ok {
			concretedCluster.UpdateHosts(hosts)
		}
	}
	
	return nil
}
```

3.2 的问题，在 [issue94]{https://github.com/alipay/sofa-mosn/issues/94}
