### ISSUE TITLE
Questions about integrate with Istio

### ISSUE THREAD

**Issue by jukylin** [alipay/sofa-mosn#124]
你好，我在文档中了解到mosn会和istio集成。但不太了解你们具体的集成。也看了你们现在源码还不能和istio的控制平面使用。因为之前学习过istio控制平面的源码[istio源码分析](https://github.com/jukylin/blog)，所以想能不能做点什么，因为我比较期待用go实现一个数据平面。

**Comment by junxiong** [comment]
目前和 istio 的集成工作还不是很完善，mosn 还只能作为数据平面的 sidecar 使用，ingress 和 Proxy 模式还需要继续使用 envoy。请看一下 #120， #126， #121 这几个 Issue，欢迎贡献代码。

**Comment by junxiong** [comment]
我们会在 sofa-mesh 项目开展 istio 集成 sofa-mosn 的工作，预计八月份完成，请移步 sofa-mesh 参与讨论或贡献代码。 另外，service mesher 微信群已经加到四群了，可以了联系宋进超进群。

**Comment by rootsongjc** [comment]
大家有关SOFAMosn的问题，欢迎[联系我](https://jimmysong.io/about)，加入ServiceMesher群参与讨论。
