### ISSUE TITLE
how sofa-mosn run as tcp proxy

### ISSUE THREAD

**Issue by skyitachi** [alipay/sofa-mosn#145]
how sofa-mosn run as tcp proxy， I can not find the docs， any one can give ideas

**Comment by Lingtaonju** [comment]
At this time , as Network Filter which "proxy" belongs to is imperfect , so in sofa-mosn , “GenericProxyFilterConfigFactory” is used default by hard-code.
 However, we are fixing this in issue:  https://github.com/alipay/sofa-mosn/issues/98
 after finishing this , config can be used to allocate tcp proxy.

If you need to use tcp proxy now, you can reference following which run mosn all in one:


`package main

import (
	"github.com/alipay/sofa-mosn/pkg/server"
	"github.com/alipay/sofa-mosn/pkg/server/config/proxy"
	"github.com/alipay/sofa-mosn/pkg/upstream/cluster"

	"net/http"
	_ "net/http/pprof"
	"sync"
	"github.com/alipay/sofa-mosn/pkg/log"
	"github.com/alipay/sofa-mosn/pkg/api/v2"
	"github.com/alipay/sofa-mosn/pkg/types"
	"net"
	"runtime"
)

const (
	TestListener   = "tstListener"
	MeshServerAddr = "0.0.0.0:12200"

	TestCluster    = "tstCluster"
	RealServerAddr = "127.0.0.1:8080"
)

func main() {
	runtime.GOMAXPROCS(1)
	log.InitDefaultLogger("stdout", log.INFO)

	go func() {
		// pprof server
		http.ListenAndServe("0.0.0.0:9090", nil)
	}()

	wg := sync.WaitGroup{}
	wg.Add(1)

	var srv server.Server

	go func() {
		// mesh
		cmf := &clusterManagerFilter{}
		cm := cluster.NewClusterManager(nil, nil, nil, false, false)
		srv = server.NewServer(nil, cmf, cm)
		srv.AddListener(tcpListener(), &proxy.TcpProxyFilterConfigFactory{
			Proxy: tcpProxyConfig(),
		}, nil)
		cmf.cccb.UpdateClusterConfig(clusters())
		cmf.chcb.UpdateClusterHost(TestCluster, 0, hosts("10.210.168.5:12222", "10.210.168.5:12223", "10.210.168.5:12224", "10.210.168.5:12225"))
		//cmf.chcb.UpdateClusterHost(TestCluster, 0, hosts(os.Args[1:]...))
		srv.Start()

	}()

	wg.Wait()
}

type clusterManagerFilter struct {
	cccb types.ClusterConfigFactoryCb
	chcb types.ClusterHostFactoryCb
}

func (cmf *clusterManagerFilter) OnCreated(cccb types.ClusterConfigFactoryCb, chcb types.ClusterHostFactoryCb) {
	cmf.cccb = cccb
	cmf.chcb = chcb
}

func tcpProxyConfig() *v2.TcpProxy {
	tcpProxyConfig := &v2.TcpProxy{}
	tcpProxyConfig.Routes = append(tcpProxyConfig.Routes, &v2.TcpRoute{
		Cluster: TestCluster,
	})
	tcpProxyConfig.AccessLogs = append(tcpProxyConfig.AccessLogs, &v2.AccessLog{})

	return tcpProxyConfig
}

func tcpListener() *v2.ListenerConfig {
	addr, _ := net.ResolveTCPAddr("tcp", MeshServerAddr)

	return &v2.ListenerConfig{
		Name:                    TestListener,
		Addr:                    addr,
		BindToPort:              true,
		PerConnBufferLimitBytes: 1024 * 32,
		LogPath:                 "",
		LogLevel:                uint8(log.DEBUG),
	}
}

func clusters() []v2.Cluster {
	var configs []v2.Cluster
	configs = append(configs, v2.Cluster{
		Name:                 TestCluster,
		ClusterType:          v2.SIMPLE_CLUSTER,
		LbType:               v2.LB_RANDOM,
		MaxRequestPerConn:    1024,
		ConnBufferLimitBytes: 32 * 1024,
	})

	return configs
}

func hosts(host ... string) []v2.Host {
	var hosts []v2.Host

	if len(host) == 0 {
		return []v2.Host{
			v2.Host{
				Address: RealServerAddr,
				Weight:  100,
			},
		}
	}

	for _, rs := range host {
		hosts = append(hosts, v2.Host{
			Address: rs,
			Weight:  100,
		})
	}
	return hosts
}`

**Comment by skyitachi** [comment]
thanks 👍
