### ISSUE TITLE
About Smooth reload and Smooth upgrade

### ISSUE THREAD

**Issue by liucimin** [alipay/sofa-mosn#146]
Hi，
I have watch the meetup and pdf from the service mesh meetup in beijing.
And in the <<service-mesh数据平面sofamosn深层揭秘>>, Duoxiaodong show us the 
mosn has finshed Smooth reload and Smooth upgrade.
But when i read the source code,i could not find where is the code.
I just find the action in reload is null.
![image](https://user-images.githubusercontent.com/8232349/43765756-44e99202-9a63-11e8-93bf-ed083c4748b9.png)

So should u tell me where is the code about this.Because i want to Learn how to hot upgrade in golang.
Thx

**Comment by nejisama** [comment]
we use kill -HUP for reload, you can find the code in pkg/server/serverkeeper.go:
catchSignalsCrossPlatform() and reconfigure()

**Comment by liucimin** [comment]
@nejisama 
sorry to brother u,
According to your advice，I read the tranfer.go connection.go and all about the listener , activelisten.
And in the reconfigure() the mosn just send the listener's accpt con.
And when the downstream is sofarpc , the startreadloop() will call transferRead and other function to send fd and buffer.
But when the downstream proctol,  the connection start() will not use.
SO such http2.0's connections how to transfer to the new mosn.

**Comment by ldxdl** [comment]
@liucimin Thank you for you question! Currently transfer only work with protocol built on top of MOSN's build-in IO without TLS. we will then work on TLS transfer, and see if we can handle third-party implementation with build-in IO out of MOSN framework. Further more, for stateful protocol , such as HTTP/2.0, it's really hard to transfer on-going stated data, such as hpack dic.. we prefer use HTTP/2.0 goaway frame to do that. @nejisama Please take a look on HTTP/2.0 graceful transfer and see if we can support it in 0.2.0 version, thanks.

**Comment by ldxdl** [comment]
+ @taoyuanyuan
