### ISSUE TITLE
inherit listen fd not judge port when listen more than one port

### ISSUE THREAD

**Issue by taoyuanyuan** [alipay/sofa-mosn#233]

**Comment by nejisama** [comment]
listener这个BUG 不仅仅是端口的问题造成的
currentIP := net.ParseIP(addr.String()) 和 inheritIP := net.ParseIP(il.Addr.String()) 中，net.ParseIP传的参数都是"ip+port"形式的，这种形式net.ParseIP会失败，返回nil， 但是net.IP的Equal方法中，nil是Equal nil的，所以看上去可能是端口的问题

**Comment by taoyuanyuan** [comment]
#253
