### ISSUE TITLE
Reopen: Follow the golang code specification

### ISSUE THREAD

**Issue by Lingtaonju** [alipay/sofa-mosn#25]
More specification need considered

**Comment by Lingtaonju** [comment]
1. licence 导致的 package comment 问题，参考 这个的写法https://github.com/arsham/expipe/blob/master/main.go

**Comment by Lingtaonju** [comment]
2. exported 变量/类型/方法 等的 comment 标准化，参照 
// Compile parses a regular expression and returns, if successful, a Regexp
// object that can be used to match against text.
func Compile(str string) (regexp *Regexp, err error) {
}

**Comment by Lingtaonju** [comment]
3. 去掉所有的下划线

**Comment by Lingtaonju** [comment]
4. 规范 else 中 的return用法，不标准写法：
func xxxx() xxx { 	
      if f.intercept {
		return types.FilterHeadersStatusStopIteration
	} else {
		return types.FilterHeadersStatusContinue  // 不标准，需要提出来
	}
}

**Comment by Lingtaonju** [comment]
5. 	range 写法问题
for k, _ := range input {
		keyset = append(keyset, k)
	}
=> 
for k := range input {
		keyset = append(keyset, k)
	}

**Comment by Lingtaonju** [comment]
6. 未赋值的变量默认为空值，不需要重复定义，例如下面
var old *net.TCPListener = nil

**Comment by Lingtaonju** [comment]
7. 当有多个返回值的时候，error 类型要放在最后

**Comment by Lingtaonju** [comment]
8. 使用  fmt.Errorf(...) 代替
   errors.New(fmt.Sprintf("unkown cluster %s", clusterName)), nil

**Comment by Lingtaonju** [comment]
9. context.Context 要是第一个入参(done)

**Comment by Lingtaonju** [comment]
10. 在非 main 函数以及 test 函数中，不要使用空 import ，类似
_ "sync"

**Comment by Lingtaonju** [comment]
11. error 类型的变量名，要以 errFoo 的形式出现

**Comment by Lingtaonju** [comment]
12. 接口方法接收的别名 要使用一致，例如 repi
func (repi *RateLimitPolicyEntryImpl) DisableKey() string {
	return repi.disablleKey
}

**Comment by Lingtaonju** [comment]
13. 可被导出的变量，需要单独做声明，比如不正确的做法
DefaultLogger, StartLogger *logger

**Comment by ckanner** [comment]
目录布局是否可以参考这个 https://github.com/golang-standards/project-layout

**Comment by junxiong** [comment]
Reopen this issue, since it is auto close by pull request #28, it is only partly completed.

**Comment by Lingtaonju** [comment]
15. 一些 misspell 的修改

**Comment by Lingtaonju** [comment]
16. 缩写组成字母均需要大写，api/v2/types.go:147:6: type TcpRoute should be TCPRoute

**Comment by Lingtaonju** [comment]
17. 变量定义时去掉没必要的类型声明 config/convertxds.go:44:19: should omit type map[string]bool from declaration of var supportFilter; it will be inferred from the right-hand side

**Comment by Lingtaonju** [comment]
18 . 类型定义避免带有报名， type name will be used as config.ConfigParsedCallback by other packages

**Comment by Lingtaonju** [comment]
19. 变量定义尽量都使用驼峰式

**Comment by EagleChen** [comment]
可以用`gometalinter`自动检测代码
