### ISSUE TITLE
Failed to run sofa-mesh

### ISSUE THREAD

**Issue by crystaldust** [alipay/sofa-mosn#321]
I'm trying sofa-mesh with the document [RunWithIstio.md](https://github.com/alipay/sofa-mosn/blob/master/docs/quickstart/RunWithIstio.md). After installing the crds and sofa-mesh control plane, the sidecar injector injects mosn as sidecar on my newly created pods, but the mosn binary always seems to encounter errors and keeps exiting and restarting.

Here is the logs from the sidecar:
```bash
2018-10-23T08:13:10.158871Z	info	Reconciling configuration (budget 0)
2018-10-23T08:13:10.158976Z	info	Epoch 0 starting
2018-10-23T08:13:10.159696Z	info	Mosn command: [start --config /etc/istio/proxy/envoy-rev0.json --service-cluster client-with-mosn --service-node sidecar~172.30.56.3~client-with-mosn-5b56d4ffc7-bq99s.default~default.svc.cluster.local]
2018/10/23 08:13:10 [DEBUG]register protocol:1
2018/10/23 08:13:10 [DEBUG]register protocol:2
2018/10/23 08:13:10 load config from :  /etc/istio/proxy/envoy-rev0.json
2018/10/23 08:13:10 [INFO]start by config : &{Servers:[] ClusterManager:{AutoDiscovery:false RegistryUseHealthCheck:false Clusters:[]} ServiceRegistry:{ServiceAppInfo:{AntShareCloud:false DataCenter: AppName:} ServicePubInfo:[]} RawDynamicResources:[] RawStaticResources:[]}
2018/10/23 08:13:10 [WARN]No Cluster provided in cluster config
2018/10/23 08:13:10 [INFO]xds client start
2018/10/23 08:13:10 [WARN]only random lbPoliy supported, convert to random
2018/10/23 08:13:10 [WARN]only random lbPoliy supported, convert to random
2018/10/23 08:13:10 [INFO]get 36 clusters from CDS
2018/10/23 08:13:10 [INFO]update clusters success
2018/10/23 08:13:10 [INFO]get 34 endpoints from EDS
2018/10/23 08:13:10 [INFO]update endpoints success
2018/10/23 08:13:10 [INFO]get 27 listeners from LDS
2018/10/23 08:13:10 Protocol in String Needed in Proxy Network Fitler
2018-10-23T08:13:10.262770Z	warn	Epoch 0 terminated with an error: exit status 1
2018-10-23T08:13:10.262801Z	warn	Aborted all epochs
2018-10-23T08:13:10.262835Z	error	Permanent error: budget exhausted trying to fulfill the desired configuration
2018-10-23T08:13:10.262844Z	error	cannot start the proxy with the desired configuration
2018-10-23T08:13:10.262869Z	error	
```

The file `/etc/istio/proxy/envoy-rev0.json` doesn't exist inside the sidecar container, the config object is an empty struct instance with zero values for all fields(I removed the contents of RawDynamicResources and RawStaticResources for a clearer log display). I think that should be the problem. Since neigher `DownstreamProtocol` nor `UpstreamProtocol` is defined, the config parse will complain "Protocol in String Needed in Proxy Network Fitler" as it showed in the log.

Any ideas about this?

**Comment by crystaldust** [comment]
@Lingtaonju Thanks, I'll try it and see if it works.

**Comment by nejisama** [comment]
@crystaldust if it works, pls tell us and we will close the issue

**Comment by crystaldust** [comment]
Works as expected, closing the issue @Lingtaonju @nejisama
