### ISSUE TITLE
Error on read

### ISSUE THREAD

**Issue by goerzh** [alipay/sofa-mosn#385]
### Describe the bug
Run tcpproxy-sample, log error

```
2018/11/16 15:32:26 [ERROR]Error on read. Connection = 2, Local Address = 127.0.0.1:2045, Remote Address = 127.0.0.1:46456, err = EOF
2018/11/16 15:32:26 [ERROR]Error on write. Connection = 3, Remote Address = 127.0.0.1:8080, err = writev tcp 127.0.0.1:54910->127.0.0.1:8080: use of closed network connection, conn = 0xc0004861c0
```

why?

### Environment
+ SOFAMosn master 1e29deecc4b85f4c4430d2c496170608929f1c53

**Comment by nejisama** [comment]
Close the server/client connection will get an error log like this.
The sample runs short connection, just send a request, so you got this error.
You can run sofa sample in tcp-proxy, and client use -t mode, then you will just get this error when you close the client
