### ISSUE TITLE
Build a extensible mechanism for easy extension of third-parity protocol on tcp

### ISSUE THREAD

**Issue by ldxdl** [alipay/sofa-mosn#40]
Based on current SOFARPC codec & stream, build a extensible mechanism for easy extension of third-party protocol on raw tcp.

**Comment by Lingtaonju** [comment]
# 案例

目前中间件团队同学在 mosn 中实现了 `Dubbo` 协议，从代码来看，除了 dubbo 协议自身的一些特殊逻辑以外(XCode，以及一些常量)，大部分的代码是可以复用的。
针对此，我们希望提供给 rpc 协议 扩展机制，即：

1. 协议解析完全自包含，作为包引入
2. sofa 的 stream 逻辑可以复用

基于对这个 case 的研究，有下面一些地方需要做改造

# 改造点
1. `clusterManager` 中针对不同协议的连接池，提供注册机制，考虑使用工厂方法，在需要添加协议的地方进行注册，如下所示。
    
```go
type connPollFactory func(lbCtx types.LoadBalancerContext, clusterName string) types.ConnectionPool
var connPollFactories map[types.Protocol]connPollFactory

func RegisterConnPoolFactory(protocol types.Protocol,factory connPollFactory) {
	//other
	connPollFactories[protocol] = factory
}

```

2. router 的扩展机制本身已经存在，但是目前注册的地方存在问题，需要再协议自身的 init 函数中做 `RegisterRouterConfigFactory` 这个地方要改一下


3. 协议的类型，也需要提供注册机制注册进来 ` pkg/protocol/types.go`


4. stream 这一层，本身的扩展机制是存在的，但为了尽可能复用 rpc 协议的逻辑，需要在 sofarpc 框架中提供不同协议的扩展机制，比如对 bolt、dubbo 等. 
根据 dubbo 来看，sofarpc 的 streamFactory 基本上可以复用，但是在 stream 调用具体协议的地方需要区分开，因而可以做的改动：
    4.1 streamConnFactory，指明具体的 rpc 协议类型
    即 ：
	```go
	type streamConnFactory struct{
	   // 添加一个具体的协议类型
	   protocol types.
	}
	```
	在调用 `newStreamConnection` 时，协议通过 ctx 下传下去。
	
	```go
	func newStreamConnection(context context.Context, connection types.Connection, clientCallbacks types.StreamConnectionEventListener,
	serverCallbacks types.ServerStreamConnectionEventListener) types.ClientStreamConnection {

	return &streamConnection{
		context:         context,
		connection:      connection,
		protocols:       ctx.Value(types.Protocol),
		activeStreams:   newStreamMap(context),
		clientCallbacks: clientCallbacks,
		serverCallbacks: serverCallbacks,
		logger:          log.ByContext(context),
	}
	}
	```
	
4.2 streamhelper.go 里面 关于 encodeSterilize 这个函数，因为 Build response 跟协议有关 ，因而还是需要提供一个注册机制，需要针对不同的协议来做回包

**Comment by ldxdl** [comment]
Fixed by #159
