### ISSUE TITLE
promethues 中没有mosn提交的 关于测试用例 bookinfo 的信息

### ISSUE THREAD

**Issue by wanhuhou** [alipay/sofa-mosn#417]
### Your question
promethues 中没有mosn提交的 关于测试用例 bookinfo 的信息，这是怎么回事，还有如果部署dubbo，功能上有什么区别 跟envoy基于http协议的应用

describe your question clearly

### Environment
+ SOFAMosn Version

**Comment by ldxdl** [comment]
对接promethues在开发中，预计1月迭代支持
dubbo目前是基于xprotocol来做的，xprotocol的功能可以看看具体的介绍https://skyao.io/tags/x-protocol/
