### ISSUE TITLE
there are no file in some vender

### ISSUE THREAD

**Issue by liymg** [alipay/sofa-mosn#44]
there are no file in some vender, such as gogo and lyft, and the pkg github.com/golang/protobuf is too old

**Comment by ldxdl** [comment]
Dupliacate: #12 
Will be finished by today.

**Comment by stdupp** [comment]
Also miss 'github.com/json-iterator/go'  and 'github.com/envoyproxy/go-control-plane/envoy/config/accesslog/v2' in vendor

**Comment by ldxdl** [comment]
@Lingtaonju pls take a look on this

**Comment by Lingtaonju** [comment]
@stdupp 麻烦再试一下 depensure 有的时候会被墙  然后  后面 vendor这块再 pr 的时候会严格把关
