### ISSUE TITLE
Bug on the filter example, golang run 'go build client.go' 

### ISSUE THREAD

**Issue by wanghui5257** [alipay/sofa-mosn#488]
### Describe the bug
go env
set GOARCH=amd64
set GOBIN=C:\Go\\bin
set GOCACHE=C:\Users\Walt\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\git\goeth;D:\git\sofa-mosn
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Walt\AppData\Local\Temp\go-build169269190=/tmp/go-build -gno-record-gcc-switches

 the error msg:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x95e571]

goroutine 1 [running]:
main.request()
	D:/git/sofa-mosn/examples/filter/commonrule/client.go:20 +0x161
main.main()
	D:/git/sofa-mosn/examples/filter/commonrule/client.go:30 +0x87

Process finished with exit code 2

**Comment by nejisama** [comment]
see readme.md 
https://github.com/alipay/sofa-mosn/blob/master/examples/filter/commonrule/README.md

**Comment by wanghui5257** [comment]
都是从github直接拉引用包惹的祸
