### ISSUE TITLE
building error  sofa-mosn/pkg/network

### ISSUE THREAD

**Issue by wanghui5257** [alipay/sofa-mosn#489]
# _/D_/git/sofa-mosn/pkg/network
.\connection.go:111:4: cannot use "github.com/rcrowley/go-metrics".NewCounter() (type "github.com/rcrowley/go-metrics".Counter) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter in field value:
	"github.com/rcrowley/go-metrics".Counter does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Counter
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter
.\connection.go:112:4: cannot use "github.com/rcrowley/go-metrics".NewGauge() (type "github.com/rcrowley/go-metrics".Gauge) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge in field value:
	"github.com/rcrowley/go-metrics".Gauge does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Gauge
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge
.\connection.go:113:4: cannot use "github.com/rcrowley/go-metrics".NewCounter() (type "github.com/rcrowley/go-metrics".Counter) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter in field value:
	"github.com/rcrowley/go-metrics".Counter does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Counter
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter
.\connection.go:114:4: cannot use "github.com/rcrowley/go-metrics".NewGauge() (type "github.com/rcrowley/go-metrics".Gauge) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge in field value:
	"github.com/rcrowley/go-metrics".Gauge does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Gauge
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge
.\connection.go:797:5: cannot use "github.com/rcrowley/go-metrics".NewCounter() (type "github.com/rcrowley/go-metrics".Counter) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter in field value:
	"github.com/rcrowley/go-metrics".Counter does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Counter
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter
.\connection.go:798:5: cannot use "github.com/rcrowley/go-metrics".NewGauge() (type "github.com/rcrowley/go-metrics".Gauge) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge in field value:
	"github.com/rcrowley/go-metrics".Gauge does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Gauge
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge
.\connection.go:799:5: cannot use "github.com/rcrowley/go-metrics".NewCounter() (type "github.com/rcrowley/go-metrics".Counter) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter in field value:
	"github.com/rcrowley/go-metrics".Counter does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Counter
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Counter
.\connection.go:800:5: cannot use "github.com/rcrowley/go-metrics".NewGauge() (type "github.com/rcrowley/go-metrics".Gauge) as type "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge in field value:
	"github.com/rcrowley/go-metrics".Gauge does not implement "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge (wrong type for Snapshot method)
		have Snapshot() "github.com/rcrowley/go-metrics".Gauge
		want Snapshot() "github.com/alipay/sofa-mosn/vendor/github.com/rcrowley/go-metrics".Gauge
.\transfer.go:348:12: undefined: syscall.UnixRights
.\transfer.go:360:15: undefined: unix.ParseSocketControlMessage
.\transfer.go:360:15: too many errors

**Comment by nejisama** [comment]
pls configure your go path correctly

**Comment by wanghui5257** [comment]
折腾这么久，发现我直接从github 拉那些引用包就有问题，我直接用这个项目下面的包编译运行都没问题，也就是这个项目目前还不能和github项目引用代码同步
