### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by wanghui5257** [alipay/sofa-mosn#491]
go version
go version go1.11.2 linux/amd64
root@ubuntu:/home/walt/sofa-mosn/cmd/mosn/main# go env
GOARCH="amd64"
GOBIN="/home/walt/go-release-branch.go1.11/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/walt/goeth:/home/walt/sofa-mosn"
GOPROXY=""
GORACE=""
GOROOT="/home/walt/go-release-branch.go1.11"
GOTMPDIR=""
GOTOOLDIR="/home/walt/go-release-branch.go1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build491418073=/tmp/go-build -gno-record-gcc-switches"

root@ubuntu:/home/walt/sofa-mosn/cmd/mosn/main# go build ./
# _/home/walt/sofa-mosn/cmd/mosn/main
./mosn.go:25:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/buffer"
./mosn.go:26:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/filter/network/proxy"
./mosn.go:27:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/filter/network/tcpproxy"
./mosn.go:28:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/filter/stream/faultinject"
./mosn.go:30:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/filter/stream/mixer"
./mosn.go:31:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/network"
./mosn.go:32:3: imported and not used: "github.com/alipay/sofa-mosn/pkg/protocol"
./mosn.go:35:3: conv redeclared as imported package name
	previous declaration at ./mosn.go:34:3
./mosn.go:36:3: conv redeclared as imported package name
	previous declaration at ./mosn.go:35:3
./mosn.go:40:3: sofarpc redeclared as imported package name
	previous declaration at ./mosn.go:29:3
./mosn.go:32:3: too many errors

删除 mosn.go:25——mosn.go:35 行编译通过

**Comment by nejisama** [comment]
mosn使用go1.9.2 编译
import这些包主要是为了使用其init函数，如果没有对应的init，会导致不必要的运行时错误
这些包应该都是用下划线引用的，不会存在import and not used的错误，估计是你改过代码

**Comment by wanghui5257** [comment]
没有改哦，go版本上面已经发了 go version go1.11.2 linux/amd64

**Comment by wanghui5257** [comment]
抱歉，昨天试图重现，重新弄一遍没有这个报错了
