### ISSUE TITLE
提供dubbo的sofa-mosn的配置文件

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#504]
我在扩展sofa-mosn的x-protocol的时候，我想参考一下dubbo的设计，但是dubbo在example中没有配置文件的例子，能够提供一个dobbo的例子

+ master分支最新代码

**Comment by nejisama** [comment]
Proxy的配置参考如下：
 
{
    "type": "proxy",
    "config": {
         "downstream_protocol": "X",
         "upstream_protocol": "X",
         "router_config_name":"server_router"，
         "extend_config": {
               "sub_protocol": "dubbo"
          }
}
