### ISSUE TITLE
能够提供一份配置文件详细的文档

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#505]
能够提供一份配置文件详细的文档
+ master最新

**Comment by nejisama** [comment]
examples中有部分示例可以参考

**Comment by zplinuxlover** [comment]
example中的配置文件不全，很多配置文件依赖关系，有什么选项，都没有一个完整的说明

**Comment by nejisama** [comment]
example中的配置文件，都是可以直接编译好binary以后直接运行的有效配置文件。不理解你说的依赖关系是什么

**Comment by TuoNiao** [comment]
请问，在原生的istio下，用mosn做sidecar，mosn的配置文件怎么配？
