### ISSUE TITLE
x-protocol fail to config header regex

### ISSUE THREAD

**Issue by lzp0412** [alipay/sofa-mosn#519]
### Describe the bug
在对接新的协议过程中，发现header的regex配置是失效的，debug后发现是utility.go有段代码有个bug
![image](https://user-images.githubusercontent.com/10192658/51813903-9abd3800-22f3-11e9-8f11-15998fcf604e.png)
按我理解应该改成：
![image](https://user-images.githubusercontent.com/10192658/51813951-dbb54c80-22f3-11e9-8ccd-605051eb871b.png)

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
好的，会FIX并且补充UT

**Comment by nejisama** [comment]
已经FIX
