### ISSUE TITLE
参数ClusterType需要校验

### ISSUE THREAD

**Issue by VitZhou** [alipay/sofa-mosn#55]
在cluster类中的func NewCluster(clusterConfig v2.Cluster, sourceAddr net.Addr, addedViaAPI bool) types.Cluster函数. 返回值newCluster很有可能为nil.因为clusterType没有添加校验.调用这个函数的地方也没有看到校验.

**Comment by Lingtaonju** [comment]
感谢提的issue，这块代码处理确实不够健壮 在fix中
