### ISSUE TITLE
mosn should panic when failed to create log file in startup period

### ISSUE THREAD

**Issue by AlexStocks** [alipay/sofa-mosn#556]
### Describe the bug

When mosn failed to create log file in pkg/server/handler.go:connHandler::AddOrUpudateListener -> log.NewLogger in startup period, the mosn just record a error log in pkg/mosn/starter.go:NewMosn.

### Expected behavior

Mosn should panic by log.StartLogger.Fatal instread of log.StartLogger.Errorf in pkg/mosn/starter.go:NewMosn::line144.

### Environment
+ SOFAMosn  1.1.0
+ Linux 3.19.0
+ Go version 1.12

**Comment by nejisama** [comment]
fixed
