### ISSUE TITLE
sofa-mosn中Virtual Listener该如何配置

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#566]
{
     "version_info": "2018-09-06T09:34:19Z",
     "listener": {
      "name": "virtual",
      "address": {
       "socket_address": {
        "address": "0.0.0.0",
        "port_value": 15001
       }
      },
      "filter_chains": [
       {
        "filters": [
         {
          "name": "envoy.tcp_proxy",
          "config": {
           "stat_prefix": "BlackHoleCluster",
           "cluster": "BlackHoleCluster"
          }
         }
        ]
       }
      ],
      "use_original_dst": true
     },
     "last_updated": "2018-09-06T09:34:26.262Z"
    }

这个是envoy中的配置的说明，在sofa-mosn中该如何配置呢

**Comment by nejisama** [comment]
可以参考example中的配置，如
https://github.com/alipay/sofa-mosn/blob/master/examples/codes/http-sample/config.json

**Comment by zplinuxlover** [comment]
我就是看https://zhaohuabing.com/post/2018-09-25-istio-traffic-management-impl-intro/#virtual-listener这个，我想了解A->mosn_a -> mosn_b->b，如果请求到mosn_b的时候，到mosn_b的时候，是不需要再做路由，直接将请求发送给b,这样的配置该如何写呢？

**Comment by nejisama** [comment]
这个和Envoy是类似的。
