### ISSUE TITLE
sofa mosn配置的问题

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#568]
我就是看https://zhaohuabing.com/post/2018-09-25-istio-traffic-management-impl-intro/#virtual-listener这个，我想了解A->mosn_a -> mosn_b->b，如果请求到mosn_b的时候，到mosn_b的时候，是不需要再做路由，直接将请求发送给b,这样的配置该如何写呢？

**Comment by nejisama** [comment]
#566 duplicate
