### ISSUE TITLE
sofa mosn在mac上调试，handoff_restoreddestination无法获取到透明代理前的IP和端口

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#571]
我在mac上通过fwctl设置规则，在mac上设置fwctl规则
rdr pass on en1 inet proto tcp from 10.2.0.166 to any port 20880 -> 127.0.0.1 port 16713,但是getOriginalAddr获取的结果全部是0

**Comment by nejisama** [comment]
建议在linux环境下运行mosn
