### ISSUE TITLE
sofa mosn中重试逻辑咨询

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#581]
我想咨询一下sofa-mosn中在路由，负载均衡后，发送请求失败，重试逻辑在那里呢？我没有找到重试逻辑的地方

**Comment by nejisama** [comment]
可以在Router的配置中配置简单的按次数重试。配置以后，如果后端返回错误就会重试。
判断是否需要重试的标准为返回值的Status，对于非HTTP的协议，需要实现对应的Status转换，转换为5XX的HTTP StatusCode的就会触发重试 。SofaRPC协议转换的实现参见pkg/protocol/rpc/sofarpc/mapping.go
另，目前的逻辑中建连失败不会触发重试

**Comment by zplinuxlover** [comment]
代码中是哪里，我没有找到重试的地方

**Comment by nejisama** [comment]
proxy/downstream.go中包含了重试逻辑
