### ISSUE TITLE
服务提供者重启后导致服务消费者全部请求超时问题

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#584]
我在k8s中部署一个provider和consumer,每个Pod中各有一个app和mosn,在请求过程中，我重启provider, 这时会造成consumer所有的请求全部超时，而且不具备恢复能力，哪怕provider已经正常启动，consumer也无法恢复，我认为是func (cc *clientConnection) Connect(ioEnabled bool) (err error)这个连接操作在锁中，这个连接无法成功建立，但是也不是立即失败，导致后面的请求全部超时，我们在上面扩展了thrift协议，在上线验证过程中发现的问题比较严重，目前无法线上使用

**Comment by lion-wang** [comment]
> 我在k8s中部署一个provider和consumer,每个Pod中各有一个app和mosn,在请求过程中，我重启provider, 这时会造成consumer所有的请求全部超时，而且不具备恢复能力，哪怕provider已经正常启动，consumer也无法恢复，我认为是func (cc *clientConnection) Connect(ioEnabled bool) (err error)这个连接操作在锁中，这个连接无法成功建立，但是也不是立即失败，导致后面的请求全部超时，我们在上面扩展了thrift协议，在上线验证过程中发现的问题比较严重，目前无法线上使用

你们扩展的thrift协议可以发我学习下么？
