### ISSUE TITLE
where can find dubbo lightweight client sdk?

### ISSUE THREAD

**Issue by zhengzepeng** [alipay/sofa-mosn#594]
I just want to know how dubbo lightweight client sdk work in sofamosn?Please help!Thx...

**Comment by nejisama** [comment]
we have examples in sofa-mesh used dubbo, you can see https://github.com/alipay/sofa-mesh/tree/master/tests/e2e/tests/x-protocol/dubbo

simple dubbo example/sdk  like sofa rpc in our test is in developing

**Comment by zhengzepeng** [comment]
> we have examples in sofa-mesh used dubbo, you can see https://github.com/alipay/sofa-mesh/tree/master/tests/e2e/tests/x-protocol/dubbo
> 
> simple dubbo example/sdk like sofa rpc in our test is in developing

thank you~
