### ISSUE TITLE
构建镜像报错

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#596]
用master分支使用make image构建镜像报错，

RUN yum install -y \
       ssh wget curl perl logrotate make build-essential procps  gcc gcc-c++ glibc\
       sar tcpdump mpstat iostat vmstat sysstat unzip \
       python-setuptools; yum clean all

这里面要添加上gcc的依赖

**Comment by nejisama** [comment]
你好，目前MOSN的镜像均在sofamesh（https://github.com/alipay/sofa-mesh）中进行构建，作为sofa-mesh的sidecar，对应的镜像为sofastack/proxyv2

**Comment by nejisama** [comment]
这个make image的问题我们会修复一下

**Comment by nejisama** [comment]
mosn没有使用CGo相关的代码，之前make image失败是因为cpulimit的关系。
这个不是必须的，已经从里面去掉了，目前测试可以编译通过（0.4.1），不过还是建议直接使用sofa-mesh的镜像
