### ISSUE TITLE
请问是否有Xprotocol 配置daemon

### ISSUE THREAD

**Issue by xiaoxi1989** [alipay/sofa-mosn#599]
### Your question

describe your question clearly
私有RPC协议，只想完成权重，流量跟踪等轻量级需求。 是否可以提供一个daemon配置json

### Environment
+ SOFAMosn Version
master

**Comment by nejisama** [comment]
基于XProtocol的私有协议需要自己实现对应的代码

**Comment by xiaoxi1989** [comment]
@nejisama 请问有参考的相关资料吗？

**Comment by nejisama** [comment]
https://github.com/alipay/sofa-mosn/tree/master/pkg/protocol/rpc/xprotocol

**Comment by xiaoxi1989** [comment]
@nejisama 谢谢。

**Comment by xiaoxi1989** [comment]
@nejisama 请问是否有xprotocol json配置样例呢？

**Comment by xiaoxi1989** [comment]
测试了一个daemon，为什么服务端收到的数据会少了许多。测试的是jsonrpc
正常发送的报文格式：
客户端mson收到的报文
{"method":"Arith.Divide","params":[{"A":9,"B":2}],"id":0}

服务端mson收到的报文
{"methodXXXXXXXXX.Divide","params":[{"A":9,"B":2}],"id":0}
XXXX是序列化后的streamID

服务端收到的报文是
{"method.Divide","params":[{"A":9,"B":2}],"id":0}，导致消息中断。

请问下增加的streamid 是在哪个方法中去掉的呢？

**Comment by xiaoxi1989** [comment]
@nejisama

**Comment by xiaoxi1989** [comment]
AppendData 加的数据是不是应该只在mosn之间有用？在发送到server端的upstream时要去掉的吧？

**Comment by xiaoxi1989** [comment]
@pxzero 请教。。。
