### ISSUE TITLE
sendHijackReply方法

### ISSUE THREAD

**Issue by zplinuxlover** [alipay/sofa-mosn#606]
您好，我问一下你们sofa-mosn代码中的一个问题sendHijackReply方法，这个方法最终是写入encodedData，但是我没有找到从sendHijackReply往下所有可以插入的代码中可以设置encodedData的地方，能不能指点一下呢？

**Comment by nejisama** [comment]
sendHijackReply只响应了“Header”
sendHijackReplyWithBody可以添加“body”，但是目前的逻辑中只有HTTP的工作是符合预期的，SofaRPC的暂时存在一定的BUG。
你可以在pkg/proxy/downstream.go中看到说明
