### ISSUE TITLE
how to use mosn with Xprotocol in sofa mesh?

### ISSUE THREAD

**Issue by xiaoxi1989** [alipay/sofa-mosn#634]
### Your question
I have build mosn with private protocol,but no where to find any doc for integration with sofa mesh or istio.

Someone can help me ?

### Environment
+ SOFAMosn Version
0.4.1

**Comment by ldxdl** [comment]
pls see doc: https://github.com/alipay/sofa-mosn/blob/master/docs/quickstart/RunWithSOFAMesh.md

**Comment by ldxdl** [comment]
also see: https://github.com/alipay/sofa-mesh/tree/master/samples/e2e-dubbo/platform/kube

**Comment by WywTed** [comment]
When using dubbo, is there some special configuration? Is original dubbo application ok?
