### ISSUE TITLE
If i want to use mosn in sofa-mesh with version of 0.4.1, how can i do. how to build images about proxy.

### ISSUE THREAD

**Issue by WywTed** [alipay/sofa-mosn#657]
* docker.io/sofastack/proxyv2:0.3.0
* docker.io/sofastack/proxy_init:0.3.0

Is there a detail document about upgrade the version from 0.3 to 0.4 .

**Comment by junxiong** [comment]
There will be a new release next month, hopefully May 18th.

**Comment by WywTed** [comment]
Great. And is there a document about how to build proxy.

**Comment by junxiong** [comment]
bro, follow this doc https://github.com/alipay/sofa-mosn/blob/master/docs/quickstart/Setup.md
