### ISSUE TITLE
如何使用 MOSN 实现透明代理？

### ISSUE THREAD

**Issue by xxm404** [alipay/sofa-mosn#695]
### 如何使用 MOSN 实现透明代理？
MOSN 的文档对于配置没有详细的介绍，看到 Introduction 中介绍，可以实现 `Client -> MOSN -> Server` 这样的透明代理，但提供的 example 只有 `Client -> MOSN -> MOSN -> Server` 这种模型的配置文件，是否可以将 MOSN 配置成一个透明代理。

### Environment
+ SOFAMosn 0.4.2

**Comment by xxm404** [comment]
是否可以提供一个配置文件的例子呢？

**Comment by nejisama** [comment]
Client -> MOSN -> Server 的场景和Client -> MOSN -> MOSN -> Server的场景是一致的，你可以理解其中一个“MOSN”就是对应的Server即可

**Comment by xxm404** [comment]
> Client -> MOSN -> Server 的场景和Client -> MOSN -> MOSN -> Server的场景是一致的，你可以理解其中一个“MOSN”就是对应的Server即可

也就是说，MOSN 是不能单纯的当作一个 Forward Proxy 使用的是吗？MOSN 只能将 Client 的请求转发到配置文件中指定的 Server ，而不是作为一个单纯的透明代理，将 Client 的请求转发到 Client 请求的任意 Server

**Comment by nejisama** [comment]
mosn只会处理特定端口（配置）的请求，不会处理“任意”请求。
可以通过iptables配合handoff_restoreddestination配置进行“透明代理”:
假如机器A部署有一个应用，监听了端口80，可以通过mosn的配置做到让机器A收到80端口的请求都经过MOSN处理以后，再转发到应用。

**Comment by xxm404** [comment]
> mosn只会处理特定端口（配置）的请求，不会处理“任意”请求。
> 可以通过iptables配合handoff_restoreddestination配置进行“透明代理”:
> 假如机器A部署有一个应用，监听了端口80，可以通过mosn的配置做到让机器A收到80端口的请求都经过MOSN处理以后，再转发到应用。

好的，感谢！
