### ISSUE TITLE
Route's config should be validated on mosn start

### ISSUE THREAD

**Issue by ldxdl** [alipay/sofa-mosn#73]
Route's config should be validated on mosn start. All allowed rules should be workable.

**Comment by Lingtaonju** [comment]
for (const auto& route : virtual_host.routes()) {
    const bool has_prefix =
        route.match().path_specifier_case() == envoy::api::v2::route::RouteMatch::kPrefix;
    const bool has_path =
        route.match().path_specifier_case() == envoy::api::v2::route::RouteMatch::kPath;
    const bool has_regex =
        route.match().path_specifier_case() == envoy::api::v2::route::RouteMatch::kRegex;
    if (has_prefix) {
      routes_.emplace_back(new PrefixRouteEntryImpl(*this, route, factory_context));
    } else if (has_path) {
      routes_.emplace_back(new PathRouteEntryImpl(*this, route, factory_context));
    } else {
      ASSERT(has_regex);
      routes_.emplace_back(new RegexRouteEntryImpl(*this, route, factory_context));
    }


envoy 里面，prefix、path、regex 默认要有一个，我们可以也这样改改
