### ISSUE TITLE
HTTP 2 request with prefix '/' not work

### ISSUE THREAD

**Issue by ldxdl** [alipay/sofa-mosn#75]
Steps:

1. Config v2.RouterMatch with a prefix '/'
2. Start mosn with a running upstream
3. Call http://$ip/

the response code is 404 with no available router

**Comment by Lingtaonju** [comment]
这个bug通过定位发现是由于 “ http2 在handle request的时候，Header里面并没有带 host, path, query string 等信息，所以导致路由的时候找不到对应的key" 导致的。
现在已经fix
