### ISSUE TITLE
依赖包问题

### ISSUE THREAD

**Issue by yanbingwei86** [alipay/sofa-mosn#81]
能不能依赖包都打到vendor目录去，现在编译要下载依赖包很麻烦啊？感谢

**Comment by ldxdl** [comment]
Try master branch with latest code. If it's still not work, pls provide detail steps of your operation. thanks.

**Comment by yanbingwei86** [comment]
I have got the latest code from master, i try to compile mosn. The error is  
![image](https://user-images.githubusercontent.com/10648835/43128894-b30fe9b0-8f65-11e8-9241-7e2ef4f640ff.png)
![image](https://user-images.githubusercontent.com/10648835/43129038-07f0e40c-8f66-11e8-9f1f-64c3c7a02211.png)

**Comment by nejisama** [comment]
it is looks like your mosn path is not in yourt $GOPATH
you should put github.com/alipay/sofa-mosn in $GOPATH/src

**Comment by yanbingwei86** [comment]
The mosn project is in $GOPATH, but no src dir. should i create this dir and copy all project files to src dir?

**Comment by yanbingwei86** [comment]
I think make * is a better way to compile project files like c or c++ projects

**Comment by nejisama** [comment]
you can see https://github.com/golang/go/wiki/GOPATH
in this case, move the project folder to $GOPATH/src/github.com/alipay/sofa-mosn

**Comment by yanbingwei86** [comment]
thanks i solve it,  go-projects always give a different compile way
