### ISSUE TITLE
global variable Adap in cluster/clusteradapter need fix

### ISSUE THREAD

**Issue by nejisama** [alipay/sofa-mosn#94]
In pkg/upstream/cluster/clusteradapter.go defines a global variable "var Adap Adapter".
The "Adap" is an extension for cluster manager , for example, it can be used in a service discovery  extension.
It is hard to understand, should be changed to factory mode, just like the other extensions.(filter, protocol, router)

**Comment by xiaoxubeii** [comment]
I think the `Adap` in pkg/upstream/cluster/clusteradapter.go is just a adaptor or proxy to `clusterManager`, it is not a plugin kinda like `router` or `protocol `. It is unlikely to have many implementations. So it is barely acceptable.

**Comment by nejisama** [comment]
The "Adap" is an export global variable , call the Adap's function will change the cluster manager's data.
An extend package can use "Adap" to implement features like service discovery, it should be changed to a extensions like router/protocol

**Comment by nejisama** [comment]
@xiaoxubeii said is right , it is not need to change "Adap" to different implementations like router/protocol, but it should not be a global variable.

The mosn make a clusterManager in cmd/mosn/start.go: NewMosn(),  at NewClusterManager will set the global Adap, then call Adap can change the clusterManager, but the Adap can be replace by NewClusterManager, the clusterManager we want to effect is created by NewMosn.
